//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC_Pharma
{
    using System;
    using System.Collections.Generic;
    
    public partial class EczaneYarenAdmin
    {
        public string KayitNo { get; set; }
        public string Personel { get; set; }
        public string PersonelSifre { get; set; }
        public string Yetki { get; set; }
    }
}
