//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC_Pharma
{
    using System;
    using System.Collections.Generic;
    
    public partial class EczaneYarenRapor
    {
        public string RaporNo { get; set; }
        public string Rapor { get; set; }
        public string RaporTarih { get; set; }
    }
}
