//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC_Pharma
{
    using System;
    using System.Collections.Generic;
    
    public partial class EczaneGunlukKasa
    {
        public string KayıtNo { get; set; }
        public string KasaIslemTipi { get; set; }
        public Nullable<decimal> KasaIslemMiktari { get; set; }
        public string Not { get; set; }
        public string IslemTarihi { get; set; }
    }
}
