//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC_Pharma
{
    using System;
    using System.Collections.Generic;
    
    public partial class EczaneYarenBorc
    {
        public string Hasta { get; set; }
        public string BorcDurum { get; set; }
        public Nullable<decimal> Borc { get; set; }
        public Nullable<decimal> Kalan { get; set; }
        public string BorcTarih { get; set; }
        public string KapanmaTarih { get; set; }
        public string Not { get; set; }
    }
}
