//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC_Pharma
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EczCVEntities : DbContext
    {
        public EczCVEntities()
            : base("name=EczCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EczaneYaren> EczaneYaren { get; set; }
        public virtual DbSet<EczaneYarenAdmin> EczaneYarenAdmin { get; set; }
        public virtual DbSet<EczaneYarenBorc> EczaneYarenBorc { get; set; }
        public virtual DbSet<EczaneYarenRapor> EczaneYarenRapor { get; set; }
        public virtual DbSet<EczaneGunlukKasa> EczaneGunlukKasa { get; set; }
        public virtual DbSet<EczaneYarenKasaCikis> EczaneYarenKasaCikis { get; set; }
    }
}
